CREATE TABLE IF NOT EXISTS users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name VARCHAR(160) NOT NULL,
  email VARCHAR(190) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  role VARCHAR(20) NOT NULL DEFAULT 'Doctor',
  specialty VARCHAR(160) NOT NULL DEFAULT '',
  license_number VARCHAR(80) NOT NULL DEFAULT '',
  contact_number VARCHAR(80) NOT NULL DEFAULT '',
  signature_url VARCHAR(500) NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS patients (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_uid CHAR(36) NOT NULL UNIQUE,
  patient_number VARCHAR(40) NOT NULL UNIQUE,
  full_name VARCHAR(180) NOT NULL,
  age INTEGER NOT NULL,
  address VARCHAR(255) NOT NULL DEFAULT '',
  sex VARCHAR(20) NOT NULL DEFAULT '',
  civil_status VARCHAR(80) NOT NULL DEFAULT '',
  contact_number VARCHAR(40) NOT NULL DEFAULT '',
  occupation VARCHAR(120) NOT NULL DEFAULT '',
  company VARCHAR(160) NOT NULL DEFAULT '',
  email VARCHAR(190) NOT NULL DEFAULT '',
  partner_name VARCHAR(180) NOT NULL DEFAULT '',
  partner_contact_number VARCHAR(40) NOT NULL DEFAULT '',
  referred_by VARCHAR(180) NOT NULL DEFAULT '',
  age_of_menarche INTEGER NULL,
  menopause_age INTEGER NULL,
  previous_menstrual_period DATE NULL,
  period_cycle_days INTEGER NULL,
  period_duration_days INTEGER NULL,
  menstrual_amount VARCHAR(80) NOT NULL DEFAULT '',
  menstrual_pattern VARCHAR(20) NOT NULL DEFAULT '',
  sexually_active BOOLEAN NULL,
  contraception_method VARCHAR(180) NOT NULL DEFAULT '',
  height_cm DECIMAL(6,2) NULL,
  weight_kg DECIMAL(6,2) NULL,
  blood_pressure VARCHAR(40) NOT NULL DEFAULT '',
  fetal_heart_tone VARCHAR(40) NOT NULL DEFAULT '',
  last_menstrual_period DATE NULL,
  photo_url VARCHAR(500) NULL,
  sync_status VARCHAR(20) NOT NULL DEFAULT 'Pending',
  last_synced_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  archived_at TIMESTAMP NULL
);

CREATE INDEX IF NOT EXISTS ix_patients_name ON patients (full_name);
CREATE INDEX IF NOT EXISTS ix_patients_updated_sync ON patients (updated_at, sync_status);

CREATE TABLE IF NOT EXISTS clinical_records (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_uid CHAR(36) NOT NULL UNIQUE,
  patient_id INTEGER NOT NULL REFERENCES patients(id),
  doctor_id INTEGER NULL REFERENCES users(id),
  visit_date TIMESTAMP NOT NULL,
  height_cm DECIMAL(6,2) NULL,
  weight_kg DECIMAL(6,2) NULL,
  blood_pressure VARCHAR(40) NOT NULL DEFAULT '',
  fetal_heart_rate VARCHAR(40) NOT NULL DEFAULT '',
  temperature_c DECIMAL(5,2) NULL,
  chief_complaint VARCHAR(255) NOT NULL,
  diagnosis VARCHAR(255) NOT NULL,
  notes TEXT NOT NULL,
  doctor_name VARCHAR(160) NOT NULL,
  sync_status VARCHAR(20) NOT NULL DEFAULT 'Pending',
  last_synced_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_clinical_records_patient_visit ON clinical_records (patient_id, visit_date);
CREATE INDEX IF NOT EXISTS ix_clinical_records_updated_sync ON clinical_records (updated_at, sync_status);

CREATE TABLE IF NOT EXISTS lab_results (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_uid CHAR(36) NOT NULL UNIQUE,
  patient_id INTEGER NOT NULL REFERENCES patients(id),
  clinical_record_id INTEGER NULL REFERENCES clinical_records(id),
  test_name VARCHAR(180) NOT NULL,
  requested_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  result_date TIMESTAMP NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'Uploaded',
  file_url VARCHAR(500) NOT NULL,
  notes TEXT NULL,
  sync_status VARCHAR(20) NOT NULL DEFAULT 'Pending',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_lab_results_patient_requested ON lab_results (patient_id, requested_date);

CREATE TABLE IF NOT EXISTS prescriptions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_uid CHAR(36) NOT NULL UNIQUE,
  patient_id INTEGER NOT NULL REFERENCES patients(id),
  clinical_record_id INTEGER NULL REFERENCES clinical_records(id),
  issued_at TIMESTAMP NOT NULL,
  medication VARCHAR(180) NOT NULL,
  dosage VARCHAR(120) NOT NULL,
  frequency VARCHAR(120) NOT NULL,
  duration VARCHAR(120) NOT NULL,
  instructions TEXT NULL,
  prescriber VARCHAR(160) NOT NULL,
  print_count INTEGER NOT NULL DEFAULT 0,
  sync_status VARCHAR(20) NOT NULL DEFAULT 'Pending',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_prescriptions_patient_issued ON prescriptions (patient_id, issued_at);

CREATE TABLE IF NOT EXISTS prescription_items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  prescription_id INTEGER NOT NULL REFERENCES prescriptions(id) ON DELETE CASCADE,
  medication VARCHAR(180) NOT NULL,
  dosage VARCHAR(120) NOT NULL,
  frequency VARCHAR(120) NOT NULL,
  duration VARCHAR(120) NOT NULL,
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_prescription_items_prescription_order ON prescription_items (prescription_id, sort_order);

INSERT INTO prescription_items
  (prescription_id, medication, dosage, frequency, duration, sort_order)
SELECT p.id, p.medication, p.dosage, p.frequency, p.duration, 0
FROM prescriptions p
WHERE NOT EXISTS (
  SELECT 1
  FROM prescription_items pi
  WHERE pi.prescription_id = p.id
);

CREATE TABLE IF NOT EXISTS print_layouts (
  id INTEGER PRIMARY KEY,
  document_type VARCHAR(40) NOT NULL DEFAULT 'Prescription',
  document_title VARCHAR(120) NOT NULL DEFAULT 'Prescription',
  clinic_name VARCHAR(180) NOT NULL DEFAULT 'MedRec Clinic',
  doctor_name VARCHAR(160) NOT NULL DEFAULT 'Dr. Cruz',
  license_number VARCHAR(80) NOT NULL DEFAULT '',
  clinic_schedule VARCHAR(255) NOT NULL DEFAULT '',
  clinic_address VARCHAR(255) NOT NULL DEFAULT '',
  logo_url VARCHAR(500) NULL,
  logo_position VARCHAR(20) NOT NULL DEFAULT 'Left',
  details_alignment VARCHAR(20) NOT NULL DEFAULT 'Left',
  signatory_name VARCHAR(160) NOT NULL DEFAULT 'Dr. Cruz',
  signatory_title VARCHAR(120) NOT NULL DEFAULT 'OB-Gyne',
  layout_json JSONB NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ux_print_layouts_document_type UNIQUE (document_type)
);

INSERT INTO print_layouts
  (id, document_type, document_title, clinic_name, doctor_name, signatory_name, signatory_title, logo_position, details_alignment)
VALUES
  (1, 'Prescription', 'Prescription', 'MedRec Clinic', 'Dr. Cruz', 'Dr. Cruz', 'OB-Gyne', 'Left', 'Left')
ON CONFLICT (id) DO NOTHING;

INSERT INTO print_layouts
  (id, document_type, document_title, clinic_name, doctor_name, signatory_name, signatory_title, logo_position, details_alignment)
VALUES
  (2, 'Diagnosis', 'Medical Certificate', 'MedRec Clinic', 'Dr. Cruz', 'Dr. Cruz', 'OB-Gyne', 'Left', 'Left')
ON CONFLICT (id) DO NOTHING;

CREATE TABLE IF NOT EXISTS appointments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id INTEGER NOT NULL REFERENCES patients(id),
  scheduled_at TIMESTAMP NOT NULL,
  reason VARCHAR(255) NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'Scheduled',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_appointments_scheduled_status ON appointments (scheduled_at, status);

CREATE TABLE IF NOT EXISTS sync_queue (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  device_id VARCHAR(120) NOT NULL DEFAULT 'local-device',
  entity_type VARCHAR(80) NOT NULL,
  entity_id INTEGER NOT NULL,
  operation VARCHAR(20) NOT NULL,
  payload_json JSONB NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  synced_at TIMESTAMP NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'Pending',
  retry_count INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS ix_sync_queue_status_updated ON sync_queue (status, updated_at);
CREATE INDEX IF NOT EXISTS ix_sync_queue_entity ON sync_queue (entity_type, entity_id);

CREATE TABLE IF NOT EXISTS sync_runs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sync_type VARCHAR(20) NOT NULL,
  started_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  finished_at TIMESTAMP NULL,
  records_uploaded INTEGER NOT NULL DEFAULT 0,
  status VARCHAR(20) NOT NULL DEFAULT 'Running',
  message VARCHAR(255) NULL
);

-- The application creates the configured AdminLogin and DoctorLogin accounts on first login.
-- Passwords are stored as salted PBKDF2 hashes; additional doctors are created in Administration.
